FROM owasp/modsecurity-crs:nginx

RUN apt-get update && apt-get install -y --no-install-recommends \
    lsb-release \
    ca-certificates \
    curl

RUN curl -sSLo /usr/share/keyrings/deb.sury.org-php.gpg https://packages.sury.org/php/apt.gpg

RUN echo "deb [signed-by=/usr/share/keyrings/deb.sury.org-php.gpg] https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list

RUN apt-get update && apt-get install -y --no-install-recommends \
    php7.3-fpm

COPY MARIJUANA-defanged.php /var/www/html/marijuana.php
COPY custom-rules.conf /etc/nginx/modsecurity/custom-rules.conf
COPY default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD service php7.3-fpm start && nginx -g "daemon off;"

