FROM php:7.3-fpm
RUN apt-get update && apt-get install -y nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY MARIJUANA-defanged.php /var/www/html/marijuana.php
WORKDIR /var/www/html
EXPOSE 80
CMD service nginx start && php-fpm
